name: Validate Branch on PR

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - main

jobs:
  validate-branch-name:
    name: Validate PR Branch Name
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch name
        run: |
          BRANCH_NAME=${{ github.head_ref }}
          
          if [[ ! $BRANCH_NAME =~ ^feature/ ]]; then
            echo "Error: PR must be created from a branch that starts with 'feature/'. Current name: $BRANCH_NAME"
            exit 1
          else
            echo "All oks: $BRANCH_NAME"
          fi 